In [1]:
import matplotlib.pyplot as plt
import numpy as np

from sklearn.decomposition import PCA

In [2]:
X = np.array([
    [3, 2],
    [-1, 0],
    [7, 1]
])

In [3]:
X_mean = np.mean(X, axis=0)

In [4]:
X_mean

array([3., 1.])

In [5]:
X_centered = X - X_mean

In [6]:
u, s, vh = np.linalg.svd(X_centered, full_matrices=True)

In [7]:
vh

array([[-0.9915228 , -0.12993279],
       [ 0.12993279, -0.9915228 ]])

In [8]:
s

array([5.70299699, 1.2148355 ])

In [9]:
A = X_centered.T @ X_centered

In [10]:
A

array([[32.,  4.],
       [ 4.,  2.]])

In [11]:
np.linalg.eig(A)

(array([32.5241747,  1.4758253]),
 array([[ 0.9915228 , -0.12993279],
        [ 0.12993279,  0.9915228 ]]))

In [22]:
covmat = None

In [25]:
prod = np.dot(X_centered.T, X_centered, out=covmat)
np.linalg.eig(prod)

(array([32.5241747,  1.4758253]),
 array([[ 0.9915228 , -0.12993279],
        [ 0.12993279,  0.9915228 ]]))

In [12]:
pca = PCA()

pca.fit(X)

PCA()

In [13]:
pca.components_

array([[-0.9915228 , -0.12993279],
       [-0.12993279,  0.9915228 ]])

In [14]:
pca.singular_values_

array([5.70299699, 1.2148355 ])