In [1]:
import numpy as np
import matplotlib as plt

from scipy import linalg

**Programming Exercise 1**

In [2]:
a = np.array([1, 1, 0])
b = np.array([-1, 2, 5])
M = np.array([[2, -1, 0], [-1, 2, -1], [0, -1, 2]])

In [3]:
# a)
np.dot(a.T, b)

1

In [4]:
# b)
M.dot(b)

array([-4,  0,  8])

In [5]:
# c)
np.linalg.norm(b)

5.477225575051661

In [6]:
# d)
# Numpy uses LAPACK routine _gesv which uses LU factorization (dgetrf)
np.linalg.solve(M, b)

array([1.5, 4. , 4.5])

In [7]:
# Similarly done in SciPy
lu, piv = linalg.lu_factor(M)
linalg.lu_solve((lu, piv), b)

array([1.5, 4. , 4.5])

In [8]:
# e)
L = np.linalg.cholesky(M)
L

array([[ 1.41421356,  0.        ,  0.        ],
       [-0.70710678,  1.22474487,  0.        ],
       [ 0.        , -0.81649658,  1.15470054]])

In [9]:
# L * y = b
y = np.linalg.solve(L, b)
y

array([-0.70710678,  1.22474487,  5.19615242])

In [10]:
# L.H * x = y
x = np.linalg.solve(L.T.conj(), y)
x

array([1.5, 4. , 4.5])

In [11]:
# Similarly done in SciPy
c, low = linalg.cho_factor(M)
c

array([[ 1.41421356, -0.70710678,  0.        ],
       [-1.        ,  1.22474487, -0.81649658],
       [ 0.        , -1.        ,  1.15470054]])

In [12]:
linalg.cho_solve((c, low), b)

array([1.5, 4. , 4.5])